# Info
name: Tori Duckworth's Portfolio
bio: Macalester College Senior, Majors in Environmental Science & Biology, Minor in Data Science 
social media: https://www.linkedin.com/in/tori-duckworth-3a5a84328/ 

# Design 
layout: default 
theme: jekyll-theme-slate
