name: Tori Duckworth's Site 
theme: minima
bio: Macalester College Senior, Majors in Environmental Science & Biology, Minor in Data Science 
social media: https://www.linkedin.com/in/tori-duckworth-3a5a84328/ 
